version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  gacr:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: example/Dockerfile
    volumes:
      - ./tmp/pkg:/go/pkg
    depends_on:
      - redis
    environment:
     - GITHUB_TOKEN=${GITHUB_TOKEN}
