on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
name: Release
jobs:
  build:
    runs-on: normal
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GOPATH: /home/github/src
      HOME: /home/github
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false
      - name: release
        run: make release
